packages:
  - "examples/*"
  - "packages/*"
catalog:
  "@arethetypeswrong/cli": ^0.17.4
  "@fontsource-variable/inter": ^5.2.5
  "@fontsource/inter": ^5.2.5
  "@playwright/test": 1.51.1
  "@types/node": ^22.13.10
  "@types/react-dom": ^19.0.4
  "@types/react": ^19.0.12
  "@vitest/coverage-v8": ^3.1.4
  "@vitest/expect": ^3.1.4
  "astro": ^5.5.6
  "debug": ^4.4.0
  "depcheck": ^1.4.7
  "eslint": ^9.23.0
  "prettier": ^3.5.3
  "react-dom": ^19.1.0
  "react": ^19.1.0
  "satori": ^0.12.2
  "tsdown": ^0.12.3
  "typescript": ^5.8.2
  "vite": ^6.2.6
  "vitest": ^3.1.4
