packages:
  - examples/*
  - packages/*

catalog:
  "@arethetypeswrong/cli": ^0.18.2
  "@astrojs/check": ^0.9.8
  "@astrojs/preact": ^5.0.2
  "@astrojs/svelte": ^8.0.3
  "@astrojs/vue": ^6.0.1
  "@fontsource-variable/inter": 5.2.6
  "@fontsource/inter": 5.2.6
  "@playwright/test": 1.58.2
  "@types/mdast": ^4.0.4
  "@types/node": ^25.5.0
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  "@types/unist": ^3.0.3
  "@vitest/coverage-v8": ^4.1.0
  "@vitest/expect": ^4.1.0
  astro: ^6.0.8
  debug: ^4.4.3
  depcheck: ^1.4.7
  eslint: ^9.39.4
  mdast-util-mdx-jsx: ^3.2.0
  preact: ^10.28.2
  prettier: ^3.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  satori: ^0.12.2
  svelte: ^5.53.5
  tsdown: ^0.21.4
  typescript: ^5.9.3
  unified: ^11.0.5
  vfile: ^6.0.3
  vite: ^7.3.1
  vitest: ^4.1.0
  vue: ^3.5.27

catalogs:
  peers:
    "@types/mdast": 4.x.x
    "@types/react": 19.x.x
    "@types/unist": 3.x.x
    mdast-util-mdx-jsx: 3.x.x
    prettier: 3.x.x
    unified: 11.x.x
    vfile: 6.x.x

# Specifies the number of minutes that must pass after a version is published
# before pnpm will install it. For example, setting minimumReleaseAge: 1440
# ensures that only packages released at least one day ago can be installed.
#
# https://github.com/pnpm/pnpm/releases/tag/v10.16.0
minimum-release-age-exclude: 4320

# doesn't catch my invalid deps right now but hopefully that'll be fixed in the
# future.
# https://github.com/pnpm/pnpm/issues/10824
strict-peer-dependencies: true
