packages:
  - "examples/*"
  - "packages/*"
catalog:
  "@arethetypeswrong/cli": ^0.17.4
  "@astrojs/preact": "^4.0.8"
  "@astrojs/react": "^4.2.3"
  "@astrojs/svelte": "^7.0.9"
  "@astrojs/vue": "^5.0.9"
  "@fontsource-variable/inter": 5.2.6
  "@fontsource/inter": 5.2.6
  "@playwright/test": 1.51.1
  "@types/node": ^22.13.10
  "@types/react-dom": ^19.0.4
  "@types/react": ^19.0.12
  "@vitest/coverage-v8": ^3.1.4
  "@vitest/expect": ^3.1.4
  "astro": ^5.10.1
  "debug": ^4.4.0
  "depcheck": ^1.4.7
  "eslint": ^9.23.0
  "preact": ^10.26.5
  "prettier": ^3.5.3
  "react-dom": ^19.1.0
  "react": ^19.1.0
  "satori": ^0.12.2
  "svelte": "^5.25.12"
  "tsdown": ^0.12.9
  "typescript": ^5.8.2
  "vite": ^6.2.6
  "vitest": ^3.1.4
  "vue": "^3.5.13"
