name: release

on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

# Use Turborepo remote caching w/ custom cache server
env:
  TURBO_API: ${{ vars.TURBO_API }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  on-failure:
    name: Handle Test Run Failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The test workflow failed, not releasing'
  release-on-success:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.12.0
        with:
          enable-cache: true
          devbox-version: 0.14.0

      - name: Install dependencies
        run: devbox run pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: devbox run pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
